### ISSUE TITLE
Unable to connect to Power BI and Power Pivot

### ISSUE THREAD

**Issue by koalaZRH** [DaxStudio/DaxStudio#124]
Hi,
I was trying to connect to Power BI models or Power Pivot Excel files using latest DAX Studio, however in both cases I encountered issues:
- I was not able to connect to Power BI Desktop file at all
- I was not able to get any result from "Traces" section in Power Pivot Excel model.

Below the details from DAX Studio Checker and 

    Version =  v2.7.4.102

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSVersion       = 10.0.15063
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.87
    FreeMemoryGB    = 9.62

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.7.02046
    v4\Client\1033 -> 4.7.02046
    v4\Full -> 4.7.02046
    v4\Full\1033 -> 4.7.02046
    v4.0\Client -> 4.0.0.0

Checking AMO
=======================
    PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 9
    AMO : 13.0.0.0
    ADOMD : 13.0.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excel_v16
    Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.4.102, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60301
        Install 1
        InstallerPath c:\Program Files (x86)\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4M_1031
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4M_1036
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4M_1041
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4M_1046
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4M_1049
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4M_2052
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4M_3082
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1

and DAX Studio Log:

2019-01-16 10:48:57.301 +01:00 [Error] "Model.ProxyPowerPivot" "HasPowerPivotModel:Get" "One or more errors occurred." "   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at DaxStudio.UI.Model.ProxyPowerPivot.get_HasPowerPivotModel()"
2019-01-16 10:49:16.923 +01:00 [Error] "ConnectionDialogViewModel" "Connect" Error Connecting using: "Data Source=;MDX Compatibility=3;;;Application Name=DAX Studio (SSAS) - 9783f92a-b39b-478e-9e32-0bfb8a4b042a"
System.NullReferenceException: Object reference not set to an instance of an object.
   at DaxStudio.UI.RegistryHelper.SaveListToRegistry(String listName, Object currentItem, IEnumerable`1 itemList)
   at DaxStudio.UI.ViewModels.ConnectionDialogViewModel.Connect()
2019-01-16 10:56:37.875 +01:00 [Error] "MetadataPaneViewModel" "Tables" "An item with the same key has already been added." "   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ADOTabular.MetaDataVisitorCSDL.AddColumnsToTable(XmlReader rdr, ADOTabularTableCollection tables, String eEntityType)
   at ADOTabular.MetaDataVisitorCSDL.GenerateTablesFromXmlReader(ADOTabularTableCollection tabs, XmlReader rdr)
   at ADOTabular.MetaDataVisitorCSDL.ADOTabular.IMetaDataVisitor.Visit(ADOTabularTableCollection tables)
   at ADOTabular.ADOTabularTableCollection.get_InternalTableCollection()
   at ADOTabular.ADOTabularTableCollection.<GetEnumerator>d__18.MoveNext()
   at DaxStudio.UI.Model.ADOTabularModelExtensions.TreeViewTables(ADOTabularModel model, IGlobalOptions options, IEventAggregator eventAggregator)
   at DaxStudio.UI.ViewModels.MetadataPaneViewModel.<RefreshTables>b__23_0()"
2019-01-16 10:57:04.831 +01:00 [Error] "MetadataPaneViewModel" "Tables" "An item with the same key has already been added." "   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ADOTabular.MetaDataVisitorCSDL.AddColumnsToTable(XmlReader rdr, ADOTabularTableCollection tables, String eEntityType)
   at ADOTabular.MetaDataVisitorCSDL.GenerateTablesFromXmlReader(ADOTabularTableCollection tabs, XmlReader rdr)
   at ADOTabular.MetaDataVisitorCSDL.ADOTabular.IMetaDataVisitor.Visit(ADOTabularTableCollection tables)
   at ADOTabular.ADOTabularTableCollection.get_InternalTableCollection()
   at ADOTabular.ADOTabularTableCollection.<GetEnumerator>d__18.MoveNext()
   at DaxStudio.UI.Model.ADOTabularModelExtensions.TreeViewTables(ADOTabularModel model, IGlobalOptions options, IEventAggregator eventAggregator)
   at DaxStudio.UI.ViewModels.MetadataPaneViewModel.<RefreshTables>b__23_0()"
2019-01-16 10:58:18.666 +01:00 [Error] "MetadataPaneViewModel" "Tables" "An item with the same key has already been added." "   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ADOTabular.MetaDataVisitorCSDL.AddColumnsToTable(XmlReader rdr, ADOTabularTableCollection tables, String eEntityType)
   at ADOTabular.MetaDataVisitorCSDL.GenerateTablesFromXmlReader(ADOTabularTableCollection tabs, XmlReader rdr)
   at ADOTabular.MetaDataVisitorCSDL.ADOTabular.IMetaDataVisitor.Visit(ADOTabularTableCollection tables)
   at ADOTabular.ADOTabularTableCollection.get_InternalTableCollection()
   at ADOTabular.ADOTabularTableCollection.<GetEnumerator>d__18.MoveNext()
   at DaxStudio.UI.Model.ADOTabularModelExtensions.TreeViewTables(ADOTabularModel model, IGlobalOptions options, IEventAggregator eventAggregator)
   at DaxStudio.UI.ViewModels.MetadataPaneViewModel.<RefreshTables>b__23_0()"
2019-01-16 11:00:04.312 +01:00 [Error] "ConnectionDialogViewModel" "Connect" Error Connecting using: "Data Source=;MDX Compatibility=3;;;Application Name=DAX Studio (SSAS) - 569ca584-6049-4ec5-b9a8-e4e8758c52e9"
System.NullReferenceException: Object reference not set to an instance of an object.
   at DaxStudio.UI.RegistryHelper.SaveListToRegistry(String listName, Object currentItem, IEnumerable`1 itemList)
   at DaxStudio.UI.ViewModels.ConnectionDialogViewModel.Connect()
2019-01-16 11:00:34.725 +01:00 [Error] "MetadataPaneViewModel" "Tables" "An item with the same key has already been added." "   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ADOTabular.MetaDataVisitorCSDL.AddColumnsToTable(XmlReader rdr, ADOTabularTableCollection tables, String eEntityType)
   at ADOTabular.MetaDataVisitorCSDL.GenerateTablesFromXmlReader(ADOTabularTableCollection tabs, XmlReader rdr)
   at ADOTabular.MetaDataVisitorCSDL.ADOTabular.IMetaDataVisitor.Visit(ADOTabularTableCollection tables)
   at ADOTabular.ADOTabularTableCollection.get_InternalTableCollection()
   at ADOTabular.ADOTabularTableCollection.<GetEnumerator>d__18.MoveNext()
   at DaxStudio.UI.Model.ADOTabularModelExtensions.TreeViewTables(ADOTabularModel model, IGlobalOptions options, IEventAggregator eventAggregator)
   at DaxStudio.UI.ViewModels.MetadataPaneViewModel.<RefreshTables>b__23_0()"

**Comment by dgosbell** [comment]
I think the Power BI Desktop issue could be related to updates to the Desktop engine. We should have a new release in a matter of days which should fix this. There data you've pasted hasn't captured any trace errors. It's probably best to try the new release when it goes public to see if it's still the same (I'll post back to this issue when it does)

**Comment by dgosbell** [comment]
I've just published the 2.8.0 version as a release. Can you check if this fixes your Power BI Desktop connection issue?

**Comment by koalaZRH** [comment]
Thank you for the update.
Ill try in the next few days and report if that fixes the issue.

**Comment by koalaZRH** [comment]
hello, 
unfortunately I still experience the same problems.
I am unable to connect to some of the pbix files and if I am able to connect to the file, it seems that nothing  happens when I use any of the buttons from  "trace" section.
Also, similar problem occurs in Excel - "All Queries" button, brings no result ("Query Trace Started" action is initiated, but there is no outcome of it).
Im using office 365, have the latest Power BI desktop (Dec) and latest Net Framework (4.7.1)

**Comment by dgosbell** [comment]
I'm sorry, but I've never seen any of these behaviours. And these sound like possibly 3 separate issues.

1. The issue with not being able to connect to pbix files could have something to do with your model metadata (ie. Table, Column or Measure names) . The error in log above about _"an item with the same key has already been added to the collection"_ might mean there is something about the names of some of your tables that is causing this issue. Is it possible to either get an example file that you can't connect to or a list of table names from one of the problem models? Or do you have any table names that are almost identical except for accent characters or something?

2. I'm not sure why you could not start a trace against Power BI. Are you seeing a timeout or errors of any sort? The tracing code is mainly calling into the microsoft libraries, so if you are connected you should be able to trace. You could try enabling [debug logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) and see if the logs from that capture any more detail that might give me a hint as to what is happening.

3. The Excel tracing is more complex than the Power BI tracing and is handled by a different dll in DAX Studio, so maybe lets see if we can get the PowerBI stuff working first.

**Comment by koalaZRH** [comment]
Thanks a lot for taking the time looking at my issues.

1. I'll try to adjust the metadata in PowerBI files and see if that helps with the problems Im experiencing.
2. I'm able to initiate the trail (in the files I was actually able to connect to), but the trail does not produce any results. How much time should it approximately take (I know it can depend on complexity of the queries too) for average, uncomplicated files with e.g 10 queries?

**Comment by dgosbell** [comment]
I assume by "trail" you mean "trace"? it should not depend too much on the complexity of the query. The traces are published from the data source on a background thread, so you should normally see results in a second or two on a local workspace. It might take a little longer for cloud based sources like Azure AS, specially if the server is under load.

**Comment by ramakompella** [comment]
[DaxChecker.txt](https://github.com/DaxStudio/DaxStudio/files/2830991/DaxChecker.txt)
I am having a similar issue. The connect to "PBI/SSDT Model" button is grayed out all the time. I do have a PowerBI Desktop file connected to Azure Analysis Services open prior to launching DAX Studio. Please find the DAX Studio Checker log attached.

**Comment by dgosbell** [comment]
@ramakompella - no this is not a similar issue PowerPivot uses a much different connection mechanism to all the other options. If your pbix has a live connection to an AzureAS model there is no data model in the pbix file for DAX Studio to connect to. You simply need to connect DAX Studio directly to AzureAS (just put the "azureas:/.../" connection string in the Tabular Server connection box)

**Comment by Mech-Mind** [comment]
I seem to be having a similar issue with DAX Studio 2.8.2. I have Power BI desktop Version: 2.66.5376.2521 64-bit (February 2019) and am using a PBIX file that connects to Azure SQL Database. For me, most of the time even with PBI desktop launched the DAX Studio button "PBI/SSDT Model" button is grayed out and stuck in "loading". But sometimes it does show my PBIX file and I can select it but it never connects for me and errors out with something like "...check that server is running...". Could this behavior be because I am using all DirectQuery to Azure SQL DB? How do I get this to connect for me?
Thanks.

**Comment by drubiolo** [comment]
I have exactly the same issue as Mech-Mind...

**Comment by drubiolo** [comment]
[DaxStudio-20190304.log](https://github.com/DaxStudio/DaxStudio/files/2928935/DaxStudio-20190304.log)

Attached the DaxStudio log. Using DaxStudio 2.8.2. Using PBI Desktop Feb'19 in two different machines. (Also tried with alpha March'19 Windows Store PBI Desktop, with same result.)

**Comment by dgosbell** [comment]
@Mech-Mind / @drubiolo - I'm really keen to get to the bottom of this but am not currently able to reproduce this behaviour. I've tested on multiple machines using Feb'19 and earlier versions of Desktop. That "check that the server is running" error comes directly from AdomdClient and would usually indicate that the port we tried to connect to was not open.

 if you can hold down left shift while starting up DAX Studio it should enable [debug logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/)
If you then reproduce the issue and shut down DAX Studio the resulting log might give us some more information. At the very least it will list out the connection string that was used and all the ports that were detected for msmdsrv instances. If you could post a copy of a debug log it would be helpful.

You could also use the "netstat -b -n" technique from [here](https://docs.microsoft.com/en-us/power-bi/power-bi-reports-performance#deep-dive-into-query-performance-with-sql-profiler-and-power-bi-desktop)
or one of the other techniques listed [here](https://biinsight.com/four-different-ways-to-find-your-power-bi-desktop-local-port-number/) 
to see if DAX Studio appears to be finding the correct port number (it's probably easier if you just have one instance of desktop running when you do this)

**Comment by dgosbell** [comment]
@Mech-Mind / @drubiolo 0 I've found some Powershell commands that will help with trying to get to the bottom of this issue.

Could run the following in either Powershell ISE or a Powershell window after opening a report with a data model in Power BI Desktop?

$process = "MSMDSRV"
get-process -name $process | % {get-nettcpconnection -OwningProcess $_.id} | select-object @{Name="Process"; Expression = {$Process}},LocalPort, RemotePort
$process = "PBIDesktop"
get-process -name $process | % {get-nettcpconnection -OwningProcess $_.id} | select-object @{Name="Process"; Expression = {$Process}},LocalPort, RemotePort
Can you then open DAX Studio with the debug logging on(see https://daxstudio.org/documentation/troubleshooting/logging-settings/) In the debug log file there should be one or more lines like the following (depending on how many PowerBI Desktop instances you have open)

2019-03-04 20:49:09.021 -08:00 [Debug] "PowerBIHelper" "Refresh" PowerBI found on port: 51130
Could you run the following, replacing XXXX with the port number that DAX Studio found?

Get-Process -Id (Get-NetTCPConnection -LocalPort XXXX ).OwningProcess | fl * 
If DAX Studio is not getting the port number correct this may give me some hints as to why.

If you can either paste the output of the above powershell commands back here or attach it in a txt file that would help a lot.

**Comment by Mech-Mind** [comment]
Thanks for your help @dgosbell ! But go figure, today I go and hold down the shift key while I launch it and for the first time EVER it all worked as it should! I was able to pick and connect successfully to my PBI file. If it starts giving me trouble again I'll post the debug output here. Thanks again!

**Comment by drubiolo** [comment]
It happened the same to me in one machine, but still giving trouble in another.

**Comment by dgosbell** [comment]
Hmm, Has Power BI Desktop crashed at any point? I'm wondering if there is an hung process (either pbidesktop.exe or msmdsrv.exe) running that DAX Studio is finding.

If I check my machine I can see 4 msmdsrv instances as I have a local Analysis Services 2017 instance, plus a local Power BI Report Server running on my machine and 2 copies of Power BI Desktop open. (The Power BI instances are the 2 running under my user account)

![image](https://user-images.githubusercontent.com/8241830/53841714-96babf00-3ff1-11e9-829d-12398af17f9f.png)

And if I check using Process Explorer (from [ https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer ]( https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer )) I can confirm that the 2 msmdsrv instances are child processes of the PBIDesktop processes.

![image](https://user-images.githubusercontent.com/8241830/53841775-bbaf3200-3ff1-11e9-84c2-298884dd00c7.png)

If you have extra PBIDesktop.exe or msmdsrv.exe processes which you can't account for then this could be the issue and rebooting should clear this issue. 

I'd be interested to hear if a re-boot does clear this issue as I might then be able to figure out some way of detecting this situation (assuming I can find a way of simulating or force a crash in Power BI Desktop)

**Comment by Mech-Mind** [comment]
Ahh I see you may have found the issue! (latest GitHub commit) Great!

**Comment by dgosbell** [comment]
I found the Direct Query issue when connected to remote data sources thanks to some help from @drubiolo  and I've just pushed out v2.8.3 with this fix issue. Unfortunately I don't know if **all** the problems listed in this issue have been addressed, but it should fix most of them. I'm going to close this issue, if anyone still has a problem please open a new issue.
