### ISSUE TITLE
Registry error installing DaxStudio 3.0.1+

### ISSUE THREAD

**Issue by 4chinger** [DaxStudio/DaxStudio#965]
Installationprocess fails with error message:

![image](https://user-images.githubusercontent.com/114405734/192271473-e978f39b-6b41-428a-a05a-2fcfb83259e0.png)

"Select action
Error creating registry key:
HKEY_CLASSES_ROOT\daxstudio

RegCreateKeyEx failed; code 5.
access denied"

This happened first with the 3.0.1. and is the same including 3.0.4

**Comment by dgosbell** [comment]
I'm assuming that you are installing using the "Current User" option. This should be fixed in the 3.0.5 update which I just released

**Comment by 4chinger** [comment]
Hi Darren,
thanks but unfortunately the error persists the exact same way.
The install progress bar reaches the end end then this registry key access error pops up...

I assume that I am only able to do "current user" (have not had to choose anything though) because my machine is managed by IT and I do not have any Admin rights

**Comment by dgosbell** [comment]
Hi @4chinger I'm sorry but I do not know why this is not working for you. I uninstalled my copy of DAX Studio and if I try to install 3.0.4 as Current User I get the error in your screenshot. But if I install the new 3.0.5 as Current User I no longer get the error. 

Are you sure you are trying the new 3.0.5 installer?

**Comment by 4chinger** [comment]
Hi Darren,

yes I am sure...BUT did not uninstall the "old" versions I have accumulated.
What would be the best way to do that (best without use of admin rights ;-)) ?

**Comment by dgosbell** [comment]
> yes I am sure...BUT did not uninstall the "old" versions I have accumulated.

unless you have changed the path from the default the old version should have been overwritten, so this should not matter. And an old version will not impact on the installer trying to write a registry key. 

I've double checked the install script and there are definitely no references to HKEY_CLASSES_ROOT anymore.

Can you open a command prompt and go to the folder and then run the following command?

```
"DaxStudio_3_0_5_setup.exe" /log=DaxStudioSetup.log
```

This will create a log file called `DaxStudioSetup.log` - can you attach this log file back to this issue on github?

> What would be the best way to do that (best without use of admin rights ;-)) ?

You can just run the uninstall from Windows "Add or Remove programs" (just search for "Add" in your Start Menu and this should come up. If you installed without admin rights you will not need admin rights to uninstall
